# This workflow will install MLIR, Python dependencies, run tests and lint with a single version of Python

name: Tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ['3.5', '3.6', '3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3

    - name: Python Setup
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: |
        pip install --upgrade pip

    - name: Install the package locally
      run: |
        pip install -e ".[extras]"

    - name: Execute lit tests
      run: |
        lit -v tests/filecheck/ -DCOVERAGE

    - name: Combine coverage data
      run: |
        coverage combine --append
        coverage report
        coverage xml

    # - name: Upload coverage to Codecov
    #   if: matrix.python-version == '3.10'
    #   uses: Wandalen/wretry.action@v1
    #   with:
    #     action: codecov/codecov-action@v3
    #     attempt_delay: 10000
    #     attempt_limit: 10
    #     with: |
    #       fail_ci_if_error: true
    #       verbose: true
    #       directory: ${GITHUB_WORKSPACE}/../
    #       files: coverage.xml
    #       token: ${{ secrets.CODECOV_TOKEN }}
